name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev # Change this to your default branch if it's not 'main'

permissions:
  contents: write # Grant write access to the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Specify the branch to publish to
          publish_dir: ./src # Path to your static files directory
